### PR TITLE
feat: Getting started to introduce continuous integration

### PR DESCRIPTION
**Pull request by hupe1980**
**Description**
- Repository changed to monorepo
- First E2E tests with cypress were established

@oliviertassinari I think that makes it easier for us to test

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Nice! I have two questions:
- Does the test depend on the source on the repository or the published code on npm?
- What's the difference between the development and production folders?

**Comment by hupe1980** [comment]
The tests use the source code from the repository. You can change the code and run the tests without publishing to npm. In the development folder gatsby is running in development mode: HMR and NoSSR. A production build with ssr is provided in the production folder. We should always look at both, so I created the two folders.

**Comment by hupe1980** [comment]
For example, this is a test that runs only in the production folder:
https://github.com/hupe1980/gatsby-plugin-material-ui/blob/a2544f861c931690eeb3a0b08a8a5ecac6f9d312/e2e-tests/production-runtime/cypress/integration/server-side-injected-css.js#L1-L11

**Comment by oliviertassinari** [comment]
Perfect 👌

**Comment by oliviertassinari** [comment]
@hupe1980 Did you consider using an integration tool? We are using CircleCI on Material-UI side.

**Comment by hupe1980** [comment]
@oliviertassinari Yes, we should definitely use a CI tool. The repository is already linked to CircleCI. Only the configuration is missing.

**Pull request merged**
