### PR TITLE
Better CSS-in-JS library interoperability

### PR DESCRIPTION
**Pull request by trevorblades**
This pull request adds better support for using styled-components, emotion, or another CSS-in-JS library to style Material-UI components. For example:

```js
import Button from '@material-ui/core/Button';
import styled from '@emotion/styled';

const StyledButton = styled(Button)({
  backgroundColor: 'pink'
});

<StyledButton>Yo</StyledButton>
```

When websites that use this technique are run in production, the injection order of the styles generated by MUI and emotion can cause custom styles (emotion, styled-components) to be overwritten by the default MUI ones. The following GIF shows the "flash" effect that happens after the server-rendered styles are replaced with the newly injected ones:

e1074e159a77f42bbc6544b8c5838766

The MUI docs talk about this issue and explain how to fix it [here](https://material-ui.com/customization/css-in-js/#css-injection-order). This pull request implements the method described by that page. In this implementation, I used the `onClientEntry` Gatsby lifecycle API to [add a comment to the document head programatically](https://material-ui.com/customization/css-in-js/#js-createcomment).

It doesn't appear that this technique has any negative drawbacks for users _not_ mixing emotion (or others) with MUI styles, so I figured that it might as well be an out-of-the-box feature. I'd love to hear your thoughts on this idea. Would you rather it be an opt-in feature?

### CODE REVIEW

**Comment by trevorblades** [comment]
@hupe1980 good call! I've added a note about the behaviour in the README. Let me know if you think that will work.

**Comment by trevorblades** [comment]
@hupe1980 thanks for merging! Would you mind publishing a new version to npm when you've got a moment?

**Comment by oliviertassinari** [comment]
We will look into simplifying the insertion point API before the stable release of @material-ui/styles. It should be simpler! @jgoux has some nice idea in this direction.

**Comment by trevorblades** [comment]
@oliviertassinari sounds great! I'll work on an update for this library once the new insertion point API is ready to go

**Pull request merged**
